version: "2.1"
services:
  backend:
    build:
      context: ./backend
    environment:
      - MANAGEMENT_SECURITY_ENABLED=false
    ports:
      - "8081:8080"
      - "9009:9009"
    mem_limit: 300M
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    links:
      - backend
